GET http://localhost:3003/directors/:1/movies/
content-type : application/json
###


POST http://localhost:3003/movies
content-type : application/json

{
  "directorId": 6,
  "movieName": "Jurassic Park",
  "leadActor": "Jeff Goldblum"
}
###

GET http://localhost:3003/movies/48/
###

PUT http://localhost:3003/movies/56/
content-type : application/json
{
  "directorId": 24,
  "movieName": "Thor",
  "leadActor": "Christopher Hemsworth"
}
###

DELETE http://localhost:3003/movies/76/
###
